experiment:
  name: "DT"
  random_state: 23

data:
  input_dir: "data/cleaned"
  dataset_variant: "easy"
  target_column: "Target"
  label_column: "Label"

split:
  test_size: 0.2
  val_size: 0.1
  stratify: true
  load_existing_split: true
  split_dir: "data/split/easy/"

features:
  drop_columns:
    - "Label"
  remove_correlated_features: false
  correlation_threshold: 0.95
  use_feature_selection: false
  feature_selection_method: null
  selected_k_features: 40
  smote: false

model:
  criterion: gini
  max_depth: 10
  min_samples_split: 20
  min_samples_leaf: 10
  max_features: null
  class_weight: null
  ccp_alpha: 0.0

tuning_stage_1:
  enabled: false
  metric: f1
  criterion_values: ["gini", "entropy"]
  max_depth_values: [5, 10, 15, null]
  min_samples_split_values: [2, 10, 20]
  min_samples_leaf_values: [1, 5, 10]
  max_features_values: [null]
  class_weight_values: [null, "balanced"]
  ccp_alpha_values: [0.0, 0.001]

tuning_stage_2:
  enabled: false
  metric: f1
  threshold_values: [0.3, 0.4, 0.5, 0.6, 0.7]

output:
  output_dir: "outputs/decision_tree/easy/DT"
  save_metrics: true
  save_plots: true
  save_predictions: false
  save_model: false
  save_tuning_results: true
  save_best_config: true

logging:
  log_path: "logs/decision_tree/easy/DT.log"
  log_level: "INFO"