experiment:
  name: "LR-003e"
  random_state: 23

data:
  input_dir: "data/cleaned"
  dataset_variant: "easy"
  target_column: "Target"
  label_column: "Label"

split:
  test_size: 0.2
  val_size: 0.1
  stratify: true
  load_existing_split: false
  save_split: true
  split_dir: "data/split/easy/"

features:
  drop_columns:
    - "Label"
  remove_correlated_features: true
  correlation_threshold: 0.95
  use_feature_selection: false
  feature_selection_method: null
  selected_k_features: 40

preprocessing:
  smote: false
  scaling: false
  scaler: null

model:
  max_iter: 1000
  solver: "lbfgs"
  class_weight: null

output:
  output_dir: "outputs/logistic_regression/easy/LR-003"
  save_metrics: true
  save_plots: true
  save_predictions: false
  save_model: false

logging:
  log_path: "logs/logistic_regression/easy/LR-003.log"
  log_level: "INFO"