experiment:
  name: "LR-001e"
  random_state: 23

data:
  input_dir: "data/cleaned"
  dataset_variant: "easy"
  target_column: "Target"
  label_column: "Label"
  load_existing_prepared_data: false
  save_prepared_data: false
  prepared_data_dir: "data/prepared/logistic_regression/easy/LR-001"

split:
  test_size: 0.2
  val_size: 0.1
  stratify: true
  load_existing_split: false
  save_split: true
  force_regenerate_split: false
  split_dir: "data/processed/logistic_regression/easy/LR-001"

features:
  drop_columns:
    - "Label"
  remove_correlated_features: false
  correlation_threshold: 0.95
  use_feature_selection: false
  feature_selection_method: "rfe"
  selected_k_features: 40

preprocessing:
  smote: false
  scaling: false
  scaler: "standard"

model:
  max_iter: 1000
  solver: "lbfgs"
  class_weight: null

output:
  output_dir: "outputs/logistic_regression/easy/LR-001"
  save_metrics: true
  save_plots: true
  save_predictions: false
  save_model: false

logging:
  log_path: "logs/logistic_regression/easy/LR-001.log"
  log_level: "INFO"