experiment:
  name: "SVM-01e"
  random_state: 23

data:
  input_dir: "data/cleaned"
  dataset_variant: "easy"
  target_column: "Target"
  label_column: "Label"

split:
  test_size: 0.2
  val_size: 0.1
  stratify: true
  load_existing_split: true
  split_dir: "data/split/easy/"

features:
  drop_columns:
    - "Label"
  remove_correlated_features: false
  correlation_threshold: 0.95
  use_feature_selection: false
  feature_selection_method: "select_k_best" #"rfe"
  selected_k_features: 40

preprocessing:
  smote: false
  scaling: true
  scaler: "standard"

model:
  C: 1.0
  loss: "squared_hinge"
  penalty: "l2"
  dual: false
  tol: 0.0001
  max_iter: 5000
  class_weight: null
  decision_threshold: 0.0

tuning_stage_1:
  enabled: false

tuning_stage_2:
  enabled: false
  metric: f1

output:
  output_dir: "outputs/svm/easy/SVM-01e"
  summary_path: "outputs/svm/easy/svm_e_results_sum.csv"
  save_metrics: true
  save_plots: true
  save_predictions: false
  save_model: false
  save_tuning_results: true
  save_best_config: true

logging:
  log_path: "logs/svm/easy/SVM-01e.log"
  log_level: "INFO"